### ISSUE TITLE
where is the file 'Results/AnimeDemo',please?

### ISSUE THREAD

**Issue by 544211707** [proroklab/gnn_pathplanning#1]
When I try to 'Visualization',I can't find where the 'Results/AnimeDemo' is.
or May I need to produce it by myself?

**Comment by 544211707** [comment]
I understand, because when testing the trained network, I did not set it as the corresponding folder in JSON. Here is my corrected JSON:
  "data_root": "/home/fine/gnn_pathplanning/downmodel/data",
  "save_data": "/home/fine/gnn_pathplanning/downmodel/trainednetwork",
  "save_tb_data": "/home/fine/gnn_pathplanning/downmodel/1",

And when ‘Visualization’,corresponding folder is needed in the parser.

**Comment by ZiqiTIAN** [comment]
hi, I trained the network but I did not find the "successCases_ID00000.yaml" in "Result/AnimeDemo". Is there anything I ignored? I did change the PathtoCase.

**Comment by 544211707** [comment]
> hi, I trained the network but I did not find the "successCases_ID00000.yaml" in "Result/AnimeDemo". Is there anything I ignored? I did change the PathtoCase.

After training, you need to go to a deeper file directory to find them. Please refer to my path:

parser.add_argument("--map", help="input file containing map",default='/home/fine/gnn_pathplanning/downmodel/trainednetwork/Results_best/AnimeDemo/dcpOE'
                                                                          '/map20x20_rho1_10Agent/K3_HS0/TR_M20p1_10Agent/1582034757/commR_6/input/successCases_ID00007.yaml')
    #parser.add_argument("--schedule", help="schedule for agents")
    parser.add_argument("--schedule", help="schedule for agents",default='/home/fine/gnn_pathplanning/downmodel/trainednetwork/Results_best/AnimeDemo/dcpOE'
                                                                         '/map20x20_rho1_10Agent/K3_HS0/TR_M20p1_10Agent/1582034757/commR_6/predict_success/successCases_ID00007.yaml')
    #parser.add_argument("--GSO", help="record of adjacency matrix for agents")
    parser.add_argument("--GSO", help="record of adjacency matrix for agents",default='/home/fine/gnn_pathplanning/downmodel/trainednetwork/Results_best/AnimeDemo'
                                                                                      '/dcpOE/map20x20_rho1_10Agent/K3_HS0/TR_M20p1_10Agent/1582034757/commR_6/GSO/successCases_ID00007.mat')
