### ISSUE TITLE
keep getting - AllReachGoal-False

### ISSUE THREAD

**Issue by yilitai** [proroklab/gnn_pathplanning#5]
Getting AllReachGoal-False
----------------------------------------
Hi, I am a student who just begining to learn gnn, and I try to reproduce the results you get in the paper using the code you post on the repo, but I keep receiving the message: AllReachGoal-False, and it seems a little weird. I just want to ask is this normal? Or I have messed up some where that causing these errors. Really appreciate if you can answer me. My email is yilitai@outlook.com but if you answer me here I will also get the message. Thank you.

Nvm, I have found the error, it seems I never acturally load the right model.

**Comment by uncle-yi** [comment]
The code I ran is this: 
"python main.py configs/dcp_onlineExpert.json --mode test --log_anime  --best_epoch --test_general --log_time_trained 1582034757   --nGraphFilterTaps 3 --map_w 20  --num_agents 10  --trained_num_agents 10 --trained_map_w 20"

**Comment by rainy1234567890** [comment]
> Hi,I have also encountered this problem. How did you solve it in the end?

**Comment by rainy1234567890** [comment]
> ## Getting AllReachGoal-False
> 
> Hi, I am a student who just begining to learn gnn, and I try to reproduce the results you get in the paper using the code you post on the repo, but I keep receiving the message: AllReachGoal-False, and it seems a little weird. I just want to ask is this normal? Or I have messed up some where that causing these errors. Really appreciate if you can answer me. My email is [yilitai@outlook.com](mailto:yilitai@outlook.com) but if you answer me here I will also get the message. Thank you.
> 
> Nvm, I have found the error, it seems I never acturally load the right model.

Hi,I have also encountered this problem. How did you solve it in the end?
